# Generated by Django 5.0.4 on 2024-04-17 07:23

import django.core.validators
import tasty_recipes_app.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = []
