# Generated by Django 5.0.4 on 2024-04-17 07:24

import django.core.validators
import tasty_recipes_app.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=2,
                                message="Nickname must be at least 2 chars long!",
                            )
                        ],
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=30,
                        validators=[
                            tasty_recipes_app.profiles.models.validate_name_first_letter_capital
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=30,
                        validators=[
                            tasty_recipes_app.profiles.models.validate_name_first_letter_capital
                        ],
                    ),
                ),
                ("chef", models.BooleanField(default=False)),
                ("bio", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
