# Generated by Django 5.0.4 on 2024-04-17 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=10)
                        ],
                    ),
                ),
                (
                    "cuisine_type",
                    models.CharField(
                        choices=[
                            ("FRENCH", "French"),
                            ("CHINESE", "Chinese"),
                            ("ITALIAN", "Italian"),
                            ("BALKAN", "Balkan"),
                            ("OTHER", "Other"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "ingredients",
                    models.TextField(
                        help_text="Ingredients must be separated by a comma and space."
                    ),
                ),
                ("instructions", models.TextField()),
                (
                    "cooking_time",
                    models.PositiveIntegerField(
                        help_text="Provide the cooking time in minutes.",
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=1)
                        ],
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
